### ISSUE TITLE
Program does not start on some Windows computers

### ISSUE THREAD

**Issue by cochrane** [InfoSphereAC/RoboSim#1]
For currently unknown reasons, the app does not start properly on some Windows computers. This appears to be directly related to the computer (or more specifically the Windows installation), as I have not been able to get it running on computers where it doesn't start, or reproduce the issue on ones where the app works normally. It does seem to happen more with Windows XP; at least I haven't heard any other reports for newer systems.

This is not related to OpenGL drivers. The crash appears before the OpenGL system starts up.

**Comment by thiemol** [comment]
Workaround so fare is to start the simulator in admin and windows XP campatible mode.
I'll do a list of Devices, that are tested with the simulator.

**Comment by thiemol** [comment]
Try to turn off aggressive Firewalls like Avast etc., then the Simulator should also run under Windows 10.
